# -*- coding: utf-8 -*-
"""lab-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HCO2J_XTVWB9r3b7dVY_8rtid0N7XN1z
"""

a = int(input('Enter number-1: '))
b = int(input('Enter number-2: '))
x = a if a>b else b
print(x)

a = int(input('Enter number-1: '))
if a != 0:
  x=print('Positive') if a>0 else print('N
  egative')
else:
  print('Zero')

a = int(input('Enter number-1: '))
if a<=12:
  print('Child')
elif 12<a<19:
  print('Teenage')
elif 19<=a<59:
  print('Adult')
else:
  print('Senior Citizen')

a = int(input('Enter number: '))
if a==1:
  print('Monday')
elif a==2:
  print('Tuesday')
elif a==3:
  print('Wednesday')
elif a==4:
  print('Thusday')
elif a==5:
  print('Friday')
elif a==6:
  print('Saturday')
elif a==7:
  print('Sunday')
else:
  print('Invalid number my dear , try again...')

a = int(input('Enter marks : '))
b = int(input('Enter marks : '))
c = int(input('Enter marks : '))
avg = int((a+b+c)/3)
print(avg)
if avg in range(90,100):
  print('A')
elif avg in range(80,90):
  print('B')
elif avg in range(70,80):
  print('C')
elif avg in range(60,70):
  print('D')
else:
  print('F')

a = int(input('Enter a : '))
b = int(input('Enter b : '))
c = int(input('Enter c : '))
d=(b**2)-(4*a*c)
if d<0:
  print('There is no root posibble')
else:
  r1 = (-b+d)/(2*a)
  r2 = (-b-d)/(2*a)
  print(r1)
  print(r2)

a = int(input('Enter a : '))
b = int(input('Enter b : '))
c = int(input('Enter c : '))
l = [a,b,c]
l.sort()
print(l)

a = int(input('Enter a : '))
b = int(input('Enter b : '))
c = int(input('Enter c : '))
l = [a,b,c]
l.sort()
print(l[-1])

vo = ['a','e','i','o','u']
a = input('Enter a : ')
if a in vo:
  print(f"{a} is vovel")
else:
    print(f"{a} is not a vovel")

year = int(input('Enter year'))
if ( year%4==0):
  if((year % 100 == 0  and year % 400 != 0)):
     print('not leap year')
  else:
    print('Leap year')
else:
 # print('not leap year')

