# -*- coding: utf-8 -*-
"""lab-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UaEDf8EEl4EcSjFvWZjNZWq4Pl4fCQZN
"""

for i in range(-1,21):
  print(i)

type([])

type({
})

a='''hello ther I am string '''
type(a)

print(bin(12))

a=input('enter')
type(a)

c=3+4j
print(type(c))

