# -*- coding: utf-8 -*-
"""lab-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q4wSi9g4hF4v0n1JABQYQaGzVDqAd9Fp
"""

st = input('Enter Your String : ')
for i in range(0,len(st)):
  x=st[i:]
  z=st[:i]
  print(x+z)

st = input('Enter Your String : ')
up=0
lw=0
dig=0
sp=0
for i in range(0,len(st)):
  if st[i].isupper():
    up+=1
  elif st[i].isdigit():
    dig+=1
  elif st[i].islower():
    lw+=1
  else :
    sp+=1
print(f"Upper = {up}\nLower = {lw}\nDigit = {dig}\nSpaces = {sp}")

st = input('Enter Your String : ')
fullname = st[0] + '.'
for i in range(0,len(st)):
  if st[i]==" ":
    fullname+= st[i+1] + "."
print(fullname)

st = int(input('Enter Your length: '))
ml = []
for i in range(0,st):
  data = int(input('Enter num : '))
  ml.append(data)
max = ml[0]
for i in range(0,st):
  if(ml[i]>max):max=ml[i]
print(max)

def rotate(a):
  temp = a[0]
  for i in range(0,len(a)-1):
    a[i]=a[i+1]
  a[-1]=temp
  return a


ex_list = ['a','b','c','d']
print(rotate(ex_list))

matrix = [[1,2,3],[4,5,6],[7,8,9]]
for i in range(0,len(matrix)):
  sum = 0
  for j in range(0,len(matrix[i])):
    sum += matrix[i][j]
  print(f"Row of {i+1} sum is {sum}")



