# -*- coding: utf-8 -*-
"""Lab-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNj1sR_2WyRDx0U40jbayFxjuThbauOm
"""

a=int(input('Enter Number: '))
print(f"Sum is : {a*(a+1)/2}")

a=int(input('Enter base: '))
b=int(input('Enter power: '))
print(a**b)

a=input('Enter Number: ')
x=int(len(a))
a=int(a)
for i in range(0,x):
  b=int(a%10)
  if(b != 0):
    print(b)
  a=a/10

a=int(input('Enter Number: '))
s=1
for x in range(2,a+1):
  if x%2==0:
    s=s-(1/x)
  else:
    s=s+(1/x)
print(s)

import random
ran = random.randint(0,100)
tr=0
while True:
  a=int(input('Enter Number: '))
  tr=tr+1
  if a==ran:
    print(f"You guessed it right number is {ran} it took {tr} trys")
    break
  elif a<ran:
    print('Number is low')
  elif a>ran:
    print('Number is high')

def find_max(a,b,c):
  li=[a,b,c]
  li.sort()
  return li[-1]

def main():
  a=int(input('Enter Number: '))
  b=int(input('Enter Number: '))
  c=int(input('Enter Number: '))
  ans=find_max(a,b,c)
  print(ans)

main()



